### ISSUE TITLE
Toolbar of text/question-editor doesn't fold

### ISSUE THREAD

**Issue by ghost** [open-decision/open-decision#104]
On my '13 Screen, the sidebar is to small to show all possible tools in the text-editor. I would expect it to fold at some point so that I am still able to access all the tools via a drop-down.

> ![Screenshot 2021-10-11 at 11 20 57](https://user-images.githubusercontent.com/48017506/136765958-500d21b0-a321-4048-a9b3-ce340e0810fd.png)

See for example this very input field on github:
Full Screen:
> ![Screenshot 2021-10-11 at 11 25 28](https://user-images.githubusercontent.com/48017506/136766625-43153eb0-7b89-4c19-9336-28e03326b5a3.png)

Half Screen:
> ![Screenshot 2021-10-11 at 11 25 21](https://user-images.githubusercontent.com/48017506/136766619-dcc8ad2e-5d1b-4d8e-8faa-0301de7e3ce9.png)

**Comment by PhilGarb** [comment]
I agree this should not happen. It is also connected to #110. @JaRi97 could you provide a "slimmer" design for the sidebar so it is clear how to treat the elements when less space is avaliable?

**Comment by JasperRitt** [comment]
I would suggest that any symbol that takes up more space than is available can be selected in a drop-down window that appears.
<img width="446" alt="Bildschirmfoto 2021-10-13 um 19 06 08" src="https://user-images.githubusercontent.com/83953718/137180651-40e2fb94-aebb-48eb-b8b4-f5286a6ec721.png">
<img width="420" alt="Bildschirmfoto 2021-10-14 um 09 27 18" src="https://user-images.githubusercontent.com/83953718/137271153-1eca8d95-fee9-4a0d-ad5c-12d5936faf02.png">

**Comment by JasperRitt** [comment]
I think **there shouldn't be any folding in the node editor**. The node editor certainly contains our most important functionalities and can do everything the canvas can. Therefore, in my opinion, it should keep its size even on small devices. Of course, with more icons in the rich text editor, we will still have to use a "wrapping" function, as I have shown with the screenshots.

For this, **the node editor should be made a little narrower** so that it does not appear as large on small devices.

**Comment by PhilGarb** [comment]
For now we went with @JaRi97 suggestion and gave the Node Editor a fixed width. @aaronrothmann please investigate this again after the next dev rollout. I am going to close this for now. Please reopen if the issue persists or is insufficiently solved in your opinion.
