### ISSUE TITLE
Strange behavior when naming nodes

### ISSUE THREAD

**Issue by ghost** [open-decision/open-decision#105]
There is some strange behavior concerning (re)naming nodes. I cannot see a pattern at this time, so here are a few observations:

- When naming nodes, the last letter often doesn't get saved.
- The node name in the node selector and canvas are always one step behind the name one is currently typing in the name input. This feels strange when you type and then delete a character, because the deletion in the input field leads to an addition in the canvas / node selector.
- When you have a node selected and directly select another node (iE by clicking on it on the canvas), the (inactive) name input keeps the name from the old node.

**Comment by JasperRitt** [comment]
third point:
<img width="1479" alt="Bildschirmfoto 2021-10-12 um 09 33 46" src="https://user-images.githubusercontent.com/83953718/136918514-e14ad53a-dfff-455a-944e-e8e8cd173d08.png">
However, this does not happen if you closed the node editor before selecting a new node. This only happens if you select a new one with the node editor open.

**Comment by PhilGarb** [comment]
Has been fixed in 1f633f7d746b4d5543d8aca73247ffccefe343fe.
