### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by JasperRitt** [open-decision/open-decision#24]

**Comment by ghost** [comment]
I will combine all toolbar-Issues into this one. Proposed features are:

- redo and undo function
- copy (see #23)
- Multi-select
-> Function: Click on it -> icon is activated: the creator is able to click on the canvas and hold to multi select nodes
-  Fit-map-function
-> Function: click on it -> the canvas gets as big as the whole node-tree
- Zoom in/out

I myself think that Copy and multi-select are not necessary to have in the toolbar for the MVP. Those functions are easy and intuitive to use without a toolbar-button and using them with a toolbar-button might be hard to implement (what exactly happens when). What do you think?
