### ISSUE TITLE
If empty project is published, its renderer crashes

### ISSUE THREAD

**Issue by ghost** [open-decision/open-decision#254]
<img width="659" alt="Bildschirmfoto 2022-08-20 um 10 05 01" src="https://user-images.githubusercontent.com/48017506/185735976-65ea18c9-31b2-4d54-a9b0-37362f186a08.png">

**Comment by PhilGarb** [comment]
I have improved the error handling so that it does not crash. The main issue here is the way the backend determines whether a tree is empty however. See here: https://github.com/open-legal-tech/open-decision/blob/3f5ab6ee378b1fca8afcf885798261e8d8a0ab0b/apps/api/src/models/decisionTree.model.ts#L41-L45

If the tree has never been opened this works. If it has been opened, but is still without content the check fails.
