### ISSUE TITLE
Sidebar: Options & Paths Field

### ISSUE THREAD

**Issue by JasperRitt** [open-decision/open-decision#36]
- You can switch between input and options 
- Input: a free input options, e.g. for numerical values (blank field)
- Options: Any number of permanently definable answer options can be selected (more options can be added by clicking +)

**Comment by ghost** [comment]
For documentation purposes:
We talked about having a separate Areas for
- Inputs/Options: where the user can determine the possible answers of a question node
- Conditions/Paths: where the user can determine which answer leads to which next node

This might make things tidier and on first or second glance easier to handle cases where a user changes connections on Canvas. However we thought of it as repetitive and kind of counter intuitive which is why we decided against it atleast for now. 

The Input-Field should therefore now look as followed:
(I am assuming the image and it's proposed functions are self-explanatory. Feel free to ask questions)
![Screenshot 2021-08-17 at 08 49 58](https://user-images.githubusercontent.com/48017506/129677563-9e6fad0f-72b7-4c63-8917-d6f2543cddcd.png)

**Comment by PhilGarb** [comment]
@JaRi97 and me think it is sensible to add an indicator of the connected nodes to the Sidebar mainly because of the one to many relationship of connections to inputs.

That would make it clearer that there might be 10 inputs, but maybe only 3 actual connections to other nodes. Clicking on one of the connection indicators should unfold all the inputs associated with it. Additionally a way to click to quickly jump to the connected node might be interesting as well.
